config/routes.rb
Rails.application.routes.draw do
  resources :user_lesson_progressions
  require "sidekiq/web"

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    devise_for :admins, :path_names => {
      :sign_in => "login",
      :sign_up => "sign_up_to_be_an_admin"
    }
    devise_for :users, :controllers => {
      :sessions => "user/sessions",
      :registrations => "user/registrations"
    }, :path => "", :path_names => {
      :sign_in => "login",
      :sign_out => "logout",
      :password => "secret",
      :unlock => "unblock",
      :registration => "register",
      :sign_up => ""
    }, :skip => [:unlock, :confirmations]

    root "home#index"

    resources :confirmation, :only => [:index, :create]
    resources :user_preference, :only => [:index, :update], :path => "profile"
    resources :courses do
      resources :subjects, :only => [:show, :new, :create, :edit, :update, :destroy] do
        resources :lessons, :only => [:show, :new, :create, :edit, :update, :destroy] do
          resources :lesson_translations, :only => [:show, :edit, :update, :destroy], :path => "translation"
        end
      end
    end
    resources :admin, :only => [:index, :edit, :update, :destroy]

    get "/ethos" => "staticpage#ethos"
    get "/contribute" => "staticpage#contribute"
    get "/privacy" => "staticpage#privacy"

    authenticate :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end
end

app/views/admin/edit.html.erb
<h3>Edit <%= @admin.email %> </h3>

<%= simple_form_for @admin do |f| %>
  <%= f.input :email, disabled: !current_admin.superuser? %>
  <%= f.input :translator, as: :boolean, label: "Translator?", disabled: !current_admin.superuser?, required: false %>
  <%= f.input :approver, as: :boolean, label: "Approver?", disabled: !current_admin.superuser?, required: false %>
  <%= f.input :superuser, as: :boolean, label: "Super User?", disabled: !current_admin.superuser?, required: false %>
  <%= f.input :admin, as: :boolean, label: "Administrator?", disabled: !current_admin.admin?, required: false %>
  <%= f.button :submit, disabled: !current_admin.superuser? %>
<% end %>

app/views/admin/index.html.erb
<table class="table table-hover table-bordered table-responsive">
    <tr>
        <th>Email</th>
        <th>Translator</th>
        <th>Approver</th>
        <th>Super User</th>
        <th>Admin</th>
        <th>Active?</th>
        <th></th>
    </tr>
    <% @admin.each do |a| %>
        <tr class="<%= a.active? ? '' : 'table-danger' %>">
            <td><%= link_to a.email, edit_admin_path(a) %></td>
            <td><%= yesno(a.translator) %></td>
            <td><%= yesno(a.approver) %></td>
            <td><%= yesno(a.superuser) %></td>
            <td><%= yesno(a.admin) %></td>
            <td><%= yesno(a.is_active) %></td>
            <td>
                <%= link_to "Edit", edit_admin_path(a),
                    :class => "btn btn-sm btn-primary" %>
                <% if current_admin.admin? %>
                    <%= link_to "Remove", a, method: :delete,
                        data: { confirm: "Are you sure?" },
                        :class => "btn btn-sm btn-danger" %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>