config/routes.rb
Rails.application.routes.draw do
  resources :user_lesson_progressions
  require "sidekiq/web"

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    devise_for :admins, :path_names => {
      :sign_in => "login",
      :sign_up => "sign_up_to_be_an_admin"
    }
    devise_for :users, :controllers => {
      :sessions => "user/sessions",
      :registrations => "user/registrations"
    }, :path => "", :path_names => {
      :sign_in => "login",
      :sign_out => "logout",
      :password => "secret",
      :unlock => "unblock",
      :registration => "register",
      :sign_up => ""
    }, :skip => [:unlock, :confirmations]

    root "home#index"

    resources :confirmation, :only => [:index, :create]
    resources :user_preference, :only => [:index, :update], :path => "profile"
    resources :courses do
      resources :subjects, :only => [:show, :new, :create, :edit, :update, :destroy] do
        resources :lessons, :only => [:show, :new, :create, :edit, :update, :destroy] do
          resources :lesson_translations, :only => [:show, :edit, :update, :destroy], :path => "translation"
        end
      end
    end
    resources :admin, :only => [:index, :edit, :update, :destroy]

    get "/ethos" => "staticpage#ethos"
    get "/contribute" => "staticpage#contribute"
    get "/privacy" => "staticpage#privacy"

    authenticate :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end
end

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<%# Notice %>
<% if flash[:info].present? %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= flash[:info] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container">
        <span class="text-muted">© <%= Time.current.year %> Soul Medicine</span>
        <span class="pull-right">
            <% if !admin_signed_in? %>
            <%= link_to("Admin", admin_session_path) %> |
            <% end %>
            <%= icon("github") %> <%= link_to("GitHub", "https://github.com/empowerhack/soulmedicine") %> |
            <%= icon("slack") %> <%= link_to("Slack", "https://chayn.slack.com") %> |
            <%= link_to("Privacy Policy", privacy_path) %> |
            Contact
        </span>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to(t('navbar.brand'), root_path, :class => 'navbar-brand') %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= navbar_link_to( t('navbar.home'), root_path, :active_when => { :controller => "home" }) %>
      <%= navbar_link_to( t('navbar.ethos'), ethos_path, :active_when => { :action => "ethos" }) %>
      <%= navbar_link_to( t('navbar.contribute'), contribute_path, :active_when => { :action => "contribute" }) %>
      <%= navbar_link_to( t('navbar.courses'), courses_path, :active_when => { :controller => "courses" }) %>
      <% if admin_signed_in? && ( current_admin.approver? || current_admin.superuser? ) %>
        <%= navbar_link_to( "Admins", admin_index_path, :active_when => { :controller => "admin" }) %>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <%= navbar_link_to( t('navbar.profile'), user_preference_index_path, :active_when => { :controller => "user_preference" }) %>
        <%= navbar_link_to( t('navbar.log_out'), destroy_user_session_path, :method => :delete) %>
      <% elsif admin_signed_in? %>
        <%= navbar_link_to( t('navbar.log_out'), destroy_admin_session_path, :method => :delete) %>
      <% else %>
        <%= navbar_link_to( t('navbar.confirm_phone'), confirmation_index_path, :active_when => { :controller => "confirmation" }) %>
        <%= navbar_link_to( t('navbar.log_in'), new_session_path('user'), :active_when => { :controller => "user/sessions" }) %>
        <%= navbar_link_to( t('navbar.sign_up'), new_registration_path('user'), :active_when => { :controller => "devise/registrations" }) %>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarLanguage" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="hidden-sm-up">Language</span> <%= icon('language') %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarLanguage">
          <%= link_to('English', url_for( :locale => 'en' ), class: 'dropdown-item') %>
          <%= link_to('Français', url_for( :locale => 'fr' ), class: 'dropdown-item') %>
          <%= link_to('العرب', url_for( :locale => 'ar' ), class: 'dropdown-item') %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_page_header.html.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% end %>
</div>

app/views/shared/_version_table.html.erb
<div class="card">
    <h4 class="card-header">History</h4>
    <table class="table table-condensed table-bordered table-hover">
        <thead class="thead-default">
            <tr>
                <th colspan=3></th>
                <th colspan=3 class="text-center">Change</th>
            </tr>
            <tr>
                <th>Time</th>
                <th>Event</th>
                <th>By</th>
                <th>Column</th>
                <th>From</th>
                <th>To</th>
            </tr>
        </thead>
        <tbody>
            <% obj.versions.each do |version| %>
                <% version.changeset.each do |column, change| next if column.match(/_id|_at|id/) %>
                    <tr>
                        <td><%= version.created_at %></td>
                        <td><%= version.event.capitalize %></td>
                        <td><%= version.whodunnit %></td>
                        <td><%= column.capitalize %></td>
                        <td><%= change[0] %></td>
                        <td><%= change[1] %></td>
                    </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>
</div>