config/routes.rb
Rails.application.routes.draw do
  resources :user_lesson_progressions
  require "sidekiq/web"

  scope "(:locale)", :locale => /#{I18n.available_locales.join("|")}/ do
    devise_for :admins, :path_names => {
      :sign_in => "login",
      :sign_up => "sign_up_to_be_an_admin"
    }
    devise_for :users, :controllers => {
      :sessions => "user/sessions",
      :registrations => "user/registrations"
    }, :path => "", :path_names => {
      :sign_in => "login",
      :sign_out => "logout",
      :password => "secret",
      :unlock => "unblock",
      :registration => "register",
      :sign_up => ""
    }, :skip => [:unlock, :confirmations]

    root "home#index"

    resources :confirmation, :only => [:index, :create]
    resources :user_preference, :only => [:index, :update], :path => "profile"
    resources :courses do
      resources :subjects, :only => [:show, :new, :create, :edit, :update, :destroy] do
        resources :lessons, :only => [:show, :new, :create, :edit, :update, :destroy] do
          resources :lesson_translations, :only => [:show, :edit, :update, :destroy], :path => "translation"
        end
      end
    end
    resources :admin, :only => [:index, :edit, :update, :destroy]

    get "/ethos" => "staticpage#ethos"
    get "/contribute" => "staticpage#contribute"
    get "/privacy" => "staticpage#privacy"

    authenticate :admin do
      mount Sidekiq::Web => "/sidekiq"
    end
  end
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id            :integer          not null, primary key
#  name          :string           not null
#  description   :text
#  sequential_id :integer          not null
#  course_id     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  status        :integer          default("0")
#
class Subject < ApplicationRecord
  has_paper_trail :only => [:name, :description, :status]
  belongs_to :course
  acts_as_sequenced :scope => :course_id
  has_many :lessons, :dependent => :destroy

  enum :status => [:inactive, :approved, :active]

  accepts_nested_attributes_for :course, :allow_destroy => true
  accepts_nested_attributes_for :lessons, :allow_destroy => true

  # Automatically use the sequential ID in URLs
  def to_param
    sequential_id.to_s
  end

  def next
    course.subjects.find_by "subjects.sequential_id > ?", sequential_id
  end

  def prev
    course.subjects.find_by "subjects.sequential_id < ?", sequential_id
  end
end

app/controllers/subjects_controller.rb
# Subjects Controller
class SubjectsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_admin!, :except => [:show, :index]
  before_action :set_subject, :only => [:show, :edit, :update, :destroy]

  add_breadcrumb "Courses", :courses_path

  # GET /subjects/1
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @course = Course.find(params[:course_id])
    add_breadcrumb @course.name, @course
    add_breadcrumb "New Subject", new_course_subject_path
  end

  # GET /subjects/1/edit
  def edit
    add_breadcrumb @course.name, @course
    add_breadcrumb @subject.name, edit_course_subject_path(
      :course_id => @course, :id => @subject
    )
  end

  # POST /subjects
  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to course_path(
        :id => params[:course_id]
      ), :notice => "Subject was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /subjects/1
  def update
    if @subject.update(subject_params)
      redirect_to course_path(
        :id => params[:course_id]
      ), :notice => "Subject was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /subjects/1
  def destroy
    @subject.destroy
    redirect_to course_path(
      :id => params[:course_id]
    ), :notice => "Subject was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @course = Course.find_by(:sequential_id => params[:course_id])
    @subject = @course.subjects.find_by(:sequential_id => params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def subject_params
    params.require(:subject).permit(
      :name,
      :description,
      :sequential_id,
      :status,
      :course_id,
      :lessons_attributes => [
        :id,
        :name,
        :sequential_id,
        :status,
        :subject_id
      ]
    )
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= simple_form_for([@course, @subject]) do |f| %>
  <div class="row">
    <div class="col-md-2">
      <ul class="nav nav-pills flex-sm-column" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#subject" role="tab">Subject</a>
        </li>
        <% if !@subject.new_record? %>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#lessons" role="tab">Lessons</a>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-10">
      <%= error_messages_for(@subject) %>
      <div class="tab-content">
        <div class="tab-pane fade show active" id="subject" role="tabpanel">
          <%= f.input :name, :required => true %>
          <%= f.input :description, as: :text, :required => true %>
          <%= f.input :sequential_id, label: "Order", :required => true %>
          <%= f.input :course_id, as: :hidden, :input_html => { :value => @course.id } %>
          <%= f.input :status,
            collection: Subject.statuses.keys,
            :label_method => lambda { |status| status.capitalize },
            :disabled => [('approved' unless current_admin.approver?),('active' unless current_admin.superuser?)],
            :include_blank => false %>
        </div>
        <div class="tab-pane fade" id="lessons" role="tabpanel">
          <%= f.simple_fields_for :lessons do |lesson| %>
            <% render 'lessons_form', :f => lesson %>
          <% end %>
          <%= link_to "Add New Lesson",
              new_course_subject_lesson_path(@course,@subject),
              { :class=>"btn btn-sm btn-success mb-1 mt-1" } %>
        </div>
      </div>
      <%= f.button :submit, :class => "btn-block" %>
    </div>
  </div>
<% end %>

app/views/subjects/_lessons_form.html.erb
<div id="accordion" role="tablist" aria-multiselectable="false">
  <div class="card mb-1">
    <div class="card-header" role="tab" id="heading<%= f.object.id %>">
      <h5 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= f.object.id %>" aria-expanded="true" aria-controls="collapse<%= f.object.id %>">
          <%= f.object.name %>
        </a>
      </h5>
    </div>

    <div id="collapse<%= f.object.id %>" class="collapse" role="tabpanel" aria-labelledby="heading<%= f.object.id %>">
      <div class="card-block">
        <%= f.input :name %>
        <%= f.input :sequential_id, label: "Order" %>
        <%= f.input :subject_id, as: :hidden, :input_html => { :value => @subject.id } %>
        <%= f.input :status,
          collection: Lesson.statuses.keys,
          :label_method => lambda { |status| status.capitalize },
          :disabled => [('approved' unless current_admin.approver?),('active' unless current_admin.superuser?)],
          :include_blank => false %>
      </div>
      <div class="card-footer">
        <%= link_to "View Lesson and Translations",
            edit_course_subject_lesson_path(@course,@subject,f.object.sequential_id),
            { :class=>"card-link" } %>
      </div>
    </div>
  </div>
</div>

app/views/subjects/edit.html.erb
<% provide(:title, "Edit #{@subject.name}" ) %>

<%= render 'form', subject: @subject %>

<hr>

<% if current_admin.admin? && @subject.versions %>
    <%= render 'shared/version_table', :obj => @subject %>
<% end %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<% provide(:title, "New Subject" ) %>

<%= render 'form', subject: @subject %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<%= @subject.name %>

<%= link_to 'Edit', edit_course_subject_path(@subject) %> |
<%= link_to 'Back', course_path %>